version: '3.8'

services:
  # テスト環境用のアプリケーション（Firebaseエミュレータはホストで実行）
  app:
    environment:
      - NODE_ENV=test
      - FIREBASE_USE_EMULATOR=true
      - FIREBASE_AUTH_EMULATOR_HOST=host.docker.internal:9099
      - FIRESTORE_EMULATOR_HOST=host.docker.internal:8080
    network_mode: 'host'
