version: '3.8'

services:
  # テスト環境用のアプリケーション
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=test
      - FIREBASE_USE_EMULATOR=true
      - FIREBASE_AUTH_EMULATOR_HOST=localhost:9099
      - FIRESTORE_EMULATOR_HOST=localhost:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - haircut-test-network

networks:
  haircut-test-network:
    driver: bridge
