version: '3.8'

services:
  # テスト環境用のアプリケーション（Firebaseエミュレータはホストで実行）
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '13000:3000'
    environment:
      - NODE_ENV=test
      - FIREBASE_USE_EMULATOR=true
      - FIREBASE_AUTH_EMULATOR_HOST=localhost:19099
      - FIRESTORE_EMULATOR_HOST=localhost:18080
    volumes:
      - ./frontend:/app
      - /app/node_modules
