#!/bin/bash

# CEO用のコマンドヘルパー
echo "CEO コマンドヘルパー"
echo "=================="
echo ""
echo "よく使うコマンド："
echo ""
echo "1. マネージャーに新プロジェクト指示："
echo "   ./scripts/send-message.sh manager \"【プロジェクト開始指示】"
echo "   プロジェクト名：[プロジェクト名]"
echo "   目標：[具体的な目標]"
echo "   要件：[必要な機能]"
echo "   期限：[完了予定]"
echo "   このプロジェクトを成功させてください。\""
echo ""
echo "2. 進捗確認："
echo "   ./scripts/send-message.sh manager \"現在の進捗状況を報告してください。\""
echo ""
echo "3. 最終確認："
echo "   ./scripts/send-message.sh manager \"作業が完了しました。最終成果物を確認して報告してください。\""
echo ""
echo "4. 使用例 - Todoアプリ開発："
echo "   ./scripts/send-message.sh manager \"【プロジェクト開始指示】"
echo "   プロジェクト名：シンプルTodoアプリ"
echo "   目標：基本的なタスク管理機能を持つWebアプリ"
echo "   要件：タスク追加・削除・完了機能、レスポンシブデザイン"
echo "   期限：1時間以内"
echo "   このプロジェクトを成功させてください。\""