name: Claude Assistant

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  # PRレビューコメントでの手動レビュー
  claude-pr-manual-review:
    if: |
      github.event_name == 'pull_request_review_comment' &&
      contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Simple Claude Response
        run: |
          echo "Claude assistant is available for code review assistance."
          echo "Please use @claude in comments for specific help."

  # 汎用的なコメント対応
  claude-general:
    if: |
      github.event_name == 'issue_comment' &&
      contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Simple Claude Response
        run: |
          echo "Claude assistant is available for general assistance."
          echo "Please use specific commands for detailed help."
